gems: []
download_url_mac: https://s3.amazonaws.com/speak-production-releases/darwin/install-speak.dmg
bulldog_url: http://docker:9393
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      header_description: true
exclude: [
  grunt,
  vendor,
  circle.yml,
  package.json,
  Dockerfile,
  src,
  Gruntfile.js,
  deploy.sh,
  Gemfile,
  Gemfile.lock,
  README.md
]
